alias lg='lazygit'
alias zshconfig="nvim ~/.zshrc"
alias ohmyzsh="nvim ~/.oh-my-zsh"
alias f="ranger"
alias v="nvim ."
# use this with media keys later
#alias play="spotify play"
#alias pause="spotify pause"
#alias next="spotify next"
#alias prev="spotify prev"
alias gp='git add . && git commit -m "auto push" && git push'
alias config='ranger ~/.config'
alias repos='ranger ~/Repos'
alias zrc='nvim ~/.zshrc'
alias zsource='source ~/.zshrc'
alias plague='curl https://corona-stats.online/states/us'
alias p='sudo pacman -S'
alias y='yay -S'
alias set_python_path="source set_python_path"
alias cat="ccat"
alias small_text="sed -i 's/size: 22.0/size: 15.0/g' ~/.config/alacritty/alacritty.yml"
alias big_text="sed -i 's/size: 15.0/size: 22.0/g' ~/.config/alacritty/alacritty.yml"
alias monitors="xrandr -q | grep " connected" | cut -d ' ' -f1"
alias g="jump"
alias s="bookmark"
alias p="showmarks"
alias kdenlive="./Documentos/apps/kdenlive-20.08.2-x86_64.appimage"
alias olive="./Documentos/apps/Olive-33a0c2d7-Linux-x86_64.AppImage"
